# SPDX-License-Identifier: ice License 1.0

development: false
logger:
  encoder: console
  level: info
cmd/freezer-refrigerant:
  host: localhost
  version: latest
  defaultEndpointTimeout: 5s
  httpServer:
    port: 34443
    certPath: .testdata/localhost.crt
    keyPath: .testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
#TODO